version: 2
jobs:
  build:
    docker:
      - image: jonathell/multi-manager
      
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
            mvn dependency:tree
