version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: jonathell/multi-manager:1.0
      
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
            mvn install
            mvn dependency:tree      
