version: 2
jobs:
  build:
    docker:
      - image: jonathell/multi-manager:1.0
      
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
            mvn install
            mvn dependency:tree      
      - run: 
          name: run scantist scan
          command: |
            bash <(curl -s https://scripts.scantist.com/ci-circle.sh)     
      - run: 
          name: run whitesource scan
          command: |
            curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
            java -jar whitesource-fs-agent.jar -c wss-unified-agent.config -d . 
      - run: 
          name: run snyk scan
          command: |
            npm install -g snyk
            snyk -v
            snyk auth $SNYK_TOKEN
            snyk monitor
