version:2
jobs:
  build:
    working_directory: ~/example-maven-travis
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:
      - checkout
      
      - restore_cache:
        key: example-maven-travis-{{checksum "pom.xml"}}
        
      - run: mvn dependency:go-offline
      
      - save_cache:
        paths:
          - ~/.m2
        key: example-maven-travis-{{checksum "pom.xml"}}
        
      - run: mvn package
      
      
      
      
